# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: basics.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'basics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Protos.enums_pb2 as enums__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x62\x61sics.proto\x12\x14ScriptsOfTributeGRPC\x1a\x0b\x65nums.proto\"\xd4\x02\n\x04Move\x12\x30\n\x05\x42\x61sic\x18\x01 \x01(\x0b\x32\x1f.ScriptsOfTributeGRPC.BasicMoveH\x00\x12\x38\n\x08\x43\x61rdMove\x18\x02 \x01(\x0b\x32$.ScriptsOfTributeGRPC.SimpleCardMoveH\x00\x12<\n\nPatronMove\x18\x03 \x01(\x0b\x32&.ScriptsOfTributeGRPC.SimplePatronMoveH\x00\x12H\n\x0e\x43\x61rdChoiceMove\x18\x04 \x01(\x0b\x32..ScriptsOfTributeGRPC.MakeChoiceMoveUniqueCardH\x00\x12L\n\x10\x45\x66\x66\x65\x63tChoiceMove\x18\x05 \x01(\x0b\x32\x30.ScriptsOfTributeGRPC.MakeChoiceMoveUniqueEffectH\x00\x42\n\n\x08moveType\"<\n\tBasicMove\x12/\n\x07\x63ommand\x18\x01 \x01(\x0e\x32\x1e.ScriptsOfTributeGRPC.MoveEnum\"W\n\x0eSimpleCardMove\x12/\n\x07\x63ommand\x18\x01 \x01(\x0e\x32\x1e.ScriptsOfTributeGRPC.MoveEnum\x12\x14\n\x0c\x63\x61rdUniqueId\x18\x02 \x01(\x05\"u\n\x10SimplePatronMove\x12/\n\x07\x63ommand\x18\x01 \x01(\x0e\x32\x1e.ScriptsOfTributeGRPC.MoveEnum\x12\x30\n\x08patronId\x18\x02 \x01(\x0e\x32\x1e.ScriptsOfTributeGRPC.PatronId\"c\n\x18MakeChoiceMoveUniqueCard\x12/\n\x07\x63ommand\x18\x01 \x01(\x0e\x32\x1e.ScriptsOfTributeGRPC.MoveEnum\x12\x16\n\x0e\x63\x61rdsUniqueIds\x18\x02 \x03(\x05\"^\n\x1aMakeChoiceMoveUniqueEffect\x12/\n\x07\x63ommand\x18\x01 \x01(\x0e\x32\x1e.ScriptsOfTributeGRPC.MoveEnum\x12\x0f\n\x07\x65\x66\x66\x65\x63ts\x18\x02 \x03(\t\"I\n\x0c\x45ndGameState\x12\x0e\n\x06winner\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t\x12\x19\n\x11\x41\x64\x64itionalContext\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'basics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MOVE']._serialized_start=52
  _globals['_MOVE']._serialized_end=392
  _globals['_BASICMOVE']._serialized_start=394
  _globals['_BASICMOVE']._serialized_end=454
  _globals['_SIMPLECARDMOVE']._serialized_start=456
  _globals['_SIMPLECARDMOVE']._serialized_end=543
  _globals['_SIMPLEPATRONMOVE']._serialized_start=545
  _globals['_SIMPLEPATRONMOVE']._serialized_end=662
  _globals['_MAKECHOICEMOVEUNIQUECARD']._serialized_start=664
  _globals['_MAKECHOICEMOVEUNIQUECARD']._serialized_end=763
  _globals['_MAKECHOICEMOVEUNIQUEEFFECT']._serialized_start=765
  _globals['_MAKECHOICEMOVEUNIQUEEFFECT']._serialized_end=859
  _globals['_ENDGAMESTATE']._serialized_start=861
  _globals['_ENDGAMESTATE']._serialized_end=934
# @@protoc_insertion_point(module_scope)
