# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: enums.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'enums.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x65nums.proto\x12\x14ScriptsOfTributeGRPC*\x80\x01\n\x08PatronId\x12\t\n\x05\x41NSEI\x10\x00\x12\x11\n\rDUKE_OF_CROWS\x10\x01\x12\n\n\x06RAJHIN\x10\x02\x12\n\n\x06PSIJIC\x10\x03\x12\n\n\x06ORGNUM\x10\x04\x12\n\n\x06HLAALU\x10\x05\x12\t\n\x05PELIN\x10\x06\x12\r\n\tRED_EAGLE\x10\x07\x12\x0c\n\x08TREASURY\x10\x08*w\n\x08MoveEnum\x12\r\n\tPLAY_CARD\x10\x00\x12\x12\n\x0e\x41\x43TIVATE_AGENT\x10\x01\x12\n\n\x06\x41TTACK\x10\x02\x12\x0c\n\x08\x42UY_CARD\x10\x03\x12\x0f\n\x0b\x43\x41LL_PATRON\x10\x04\x12\x0f\n\x0bMAKE_CHOICE\x10\x05\x12\x0c\n\x08\x45ND_TURN\x10\x06\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'enums_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PATRONID']._serialized_start=38
  _globals['_PATRONID']._serialized_end=166
  _globals['_MOVEENUM']._serialized_start=168
  _globals['_MOVEENUM']._serialized_end=287
# @@protoc_insertion_point(module_scope)
